config/routes.rb
Rails.application.routes.draw do

  get 'api/publico/precios', to: 'products#index'

  namespace :spree do
    resources :my_pays
  end
  resources :payproxies


  # This line mounts Spree's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Spree relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.routes.draw do
    get '/spree_coinbase/redirect', :to => "coinbase#redirect", :as => :spree_coinbase_redirect
    post '/spree_coinbase/callback', :to => "coinbase#callback", :as => :spree_coinbase_callback
    get '/spree_coinbase/cancel', :to => "coinbase#cancel", :as => :spree_coinbase_cancel
    get '/spree_coinbase/success', :to => "coinbase#success", :as => :spree_coinbase_success
  end

  resources :warehouses
  resources :receipts
  resources :transactions
  resources :invoices
  resources :products
  resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #Indicar suceso de payment
  get '/payproxies/:id/sucess', to: 'payproxies#sucess'


  #Indicar fallo de payment
  get '/payproxies/:id/fail', to: 'payproxies#fail'

  # Ruteos del enunciado

  # Crear orden de compra

  # Dashboard principal
  get 'dashboard', to: 'dashboards#index'

  # Dashboard de IDs factura
  get 'dashboard/facturas', to: 'dashboards#facturas'

  # Dashboard de IDs de oc
  get 'dashboard/ordenes', to: 'dashboards#ordenes'

  put 'crear', to: 'orders#create_order'

  # Recepcionar orden de compra
  post 'oc/recepcionar/:id', to: 'orders#receive_order'
  get 'oc/recepcionar/:id', to: 'orders#receive_order'

  # Rechazar orden de compra
  post 'oc/rechazar/:id', to: 'orders#reject_order'
  get 'oc/rechazar/:id', to: 'orders#reject_order'

  # Anular orden de compra
  post 'oc/anular/:id', to: 'orders#cancel_order'
  get 'oc/anular/:id', to: 'orders#cancel_order'

  # Obtener order de compra
  # get 'obtener/:id', to: 'orders#show'
  get 'obtener/:id', to: 'orders#show_order'

  # Ruteos del banco

  # Transferir dinero
  put 'trx', to: 'transactions#transfer'

  # Obtener transaccion
  #get 'trx/:id', to: 'transactions#show'
  get 'trx/:id', to: 'transactions#show_transaction'

  # Obtener cartola
  get 'cartola', to: 'transactions#index'

  # Obtener cuenta y saldo
  get 'banco/cuenta/:id', to: 'transactions#account'


  # Ruteos de facturas

  #Crear factura
  get 'factura/crear/:id_oc', to: 'invoices#create'

  #Aceptar factura
  get 'factura/aceptar/:id_factura', to: 'invoices#accept'

  #Rechazar factura
  get 'factura/rechazar/:id_factura', to: 'invoices#reject'

  #Get factura
  get 'factura/:id_factura', to: 'invoices#get'

  #Recibir notificacion de factura
  get 'invoices/:id_factura/:bank_account', to: 'invoices#notifyFactura'
  put 'invoices/:id_factura', to: 'invoices#notifyFactura'

  # Emitir factura
  #post '', to: 'invoices#generate'

  # Obtener factura
  # get ':id', to: 'invoices#show'
  #get '1', to: 'invoices#show_invoice'

  # Rechazar factura
  #post 'reject', to: 'invoices#reject'

  # Anular factura
  #post 'cancel', to: 'invoices#cancel'

  # Crear boleta
  get 'sii/boleta/:id/:monto', to: 'invoices#pagar'
  get 'order/:id', to: 'warehouses#order_id'



  # Ruteos acordados con otros grupos

  # Obtener lista de productos
  get 'precios', to: 'products#index'


  # Notificar orden de compra (otro grupo notifica que creo una o/c para nosotros)
  put 'purchase_orders/:id', to: 'orders#notify'
  put 'test/test', to: 'orders#test'

  # Informar aceptacion de orden de compra
  post 'purchase_orders/:id', to: 'orders#accept'
  patch 'purchase_orders/:id/accepted', to: 'orders#accept'

  # Informar rechazo de orden de compra
  delete 'purchase_order/:id', to: 'orders#reject'
  patch 'purchase_orders/:id/rejected', to: 'orders#reject'

  # Enviar nueva factura
  put 'invoices', to: 'invoices#receive'
  put 'invoices/:id', to: 'invoices#receive'

  # Informar aceptacion orden de compra
  post 'invoices/:id', to: 'invoices#accept'
  patch 'invoices/:id/accepted', to: 'invoices#accept'

  # Informar rechazo factura
  delete 'invoices/:id', to: 'invoices#reject'
  patch 'invoices/:id/rejected', to: 'invoices#reject'

  # Informar envio de productos
  patch 'invoices/:id/delivered', to: 'invoices#delivered'

  # Recibir pago
  patch 'invoices/:id/paid', to: 'invoices#paid'

  # GET almacenes
  get 'getAlmacenes', to: 'warehouses#getAlmacenes'

  #GET skusWithStock
  get 'getSkusWithStock/:id', to: 'warehouses#getSkusWithStock'

  #GET stock
  get 'getStock/:id/:sku', to: 'warehouses#getStock'

  # GET inicializar
  get 'inicializar/1', to: 'warehouses#initialize1'
  get 'inicializar/2', to: 'warehouses#initialize2'
  get 'inicializar/3', to: 'warehouses#initialize3'
  get 'inicializar/4', to: 'warehouses#initialize4'
  get 'inicializar/5', to: 'warehouses#initialize5'
  get 'inicializar/primas', to: 'warehouses#initializePrimas'
  # get 'order/19', to: 'warehouses#order19'
  # get 'order/20', to: 'warehouses#order20'
  # get 'order/26', to: 'warehouses#order26'
  # get 'order/27', to: 'warehouses#order27'
  # get 'order/38', to: 'warehouses#order38'
  get 'order/:id', to: 'warehouses#order_id'
  get 'order/:id/:lotes', to: 'warehouses#order_lotes'

  # vaciar recepcion
  get 'vaciar_recepcion', to: 'warehouses#vaciar_recepcion'
  # Mover desdde general a despacho
  get 'mover_general_despacho/:sku/:cantidad', to: 'warehouses#mover_general_despacho'
  # mover dede pulmon a general.
  get 'mover_pulmon_general/:sku/:cantidad', to: 'warehouses#mover_pulmon_general'
  # Mover desdde despacho a general.
  get 'mover_despacho_general/:sku/:cantidad', to: 'warehouses#mover_despacho_general'

  get 'despachar_orden/:sku/:cantidad/:precio/:almacenId/:oc', to: 'warehouses#despachar'
  get 'despachar_orden_desde_despacho/:sku/:cantidad/:precio/:almacenId/:oc', to: 'warehouses#despachar_despacho'
  get 'despachar_aceptar/:sku/:cantidad/:precio/:almacenId/:oc', to: 'warehouses#despachar_aceptar'
  get 'aceptar_facturar_despachar/:oc/:almacenId', to: 'warehouses#aceptar_facturar_despachar'
  get 'despachar_ftp/:sku/:cantidad/:precio/:oc', to: 'warehouses#despachar_ftp'

  get 'distribuidores_dev', to: 'orders#distribuidores_dev'
  get 'distribuidores_prod', to: 'orders#distribuidores_prod'
  get 'transaccionar/:monto/:destino', to: 'invoices#transaccionar'
  get 'estado_distribuidores_dev', to: 'orders#estado_distribuidores_dev'
  get 'estado_distribuidores_prod', to: 'orders#estado_distribuidores_prod'

  get 'auto_distribuidores_dev', to: 'orders#auto_distribuidores_dev'
  get 'auto_distribuidores_prod', to: 'orders#auto_distribuidores_prod'

end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/coinbase_transaction.rb
module Spree
  class CoinbaseTransaction < ActiveRecord::Base
    has_many :payments, :as => :source

    def actions
      []
    end

  end
end

app/models/spree/gateway/iic3103pay.rb
require 'api_pago'

class Spree::Gateway::IIC3103pay  < Spree::Gateway

  def provider
    @provider = self
  end

  def provider_class
    self.class
  end

  def provider_class
    Spree::Gateway::IIC3103pay
  end

  def source_required?
    true
  end

  def confirmation_required?
    true
  end

  def payment_source_class
    Spree::CreditCard
  end

  def auto_capture?
    auto
  end

  def payment_profiles_supported?
    false
  end

  def method_type
    'iic3103pay'
  end

  def purchase(amount, transaction_details, options = {})
    puts "iic3103 - purchase #{amount}"

    response = ApiPago.pay('1', 1000)

    puts "iic3103 - pay = #{response}"


    ActiveMerchant::Billing::Response.new(response, 'success', {}, {})
  end

  def authorize(amount, transaction_details, options = {})
    puts "iic3103 - authorize #{amount}"

    response = ApiPago.pay('1', 1000)

    puts "iic3103 - pay = #{response}"


    ActiveMerchant::Billing::Response.new(response, 'success', {}, {})
  end


end

app/models/spree/my_pay.rb
class Spree::MyPay < ApplicationRecord
end

app/models/spree/payment_method/coinbase.rb
module Spree
  class PaymentMethod::Coinbase < PaymentMethod
    preference :api_key, :string
    preference :api_secret, :string
    preference :use_off_site_payment_page, :boolean

    def auto_capture?
      true
    end

    def provider_class
      nil
    end

    def payment_source_class
      nil
    end

    def source_required?
      false
    end
  end
end

app/controllers/spree/checkout_controller.rb
module Spree
  # This is somewhat contrary to standard REST convention since there is not
  # actually a Checkout object. There's enough distinct logic specific to
  # checkout which has nothing to do with updating an order that this approach
  # is waranted.
  class CheckoutController < Spree::StoreController
    before_action :load_order_with_lock
    before_action :ensure_valid_state_lock_version, only: [:update]
    before_action :set_state_if_present

    before_action :ensure_order_not_completed
    before_action :ensure_checkout_allowed
    before_action :ensure_sufficient_stock_lines
    before_action :ensure_valid_state

    before_action :associate_user
    before_action :check_authorization

    before_action :setup_for_current_state
    before_action :add_store_credit_payments, only: [:update]

    helper 'spree/orders'

    rescue_from Spree::Core::GatewayError, with: :rescue_from_spree_gateway_error

    # Updates the order and advances to the next state (when possible.)
    def update
      if @order.update_from_params(params, permitted_checkout_attributes, request.headers.env)
        @order.temporary_address = !params[:save_user_address]
        unless @order.next
          flash[:error] = @order.errors.full_messages.join("\n")
          redirect_to(checkout_state_path(@order.state)) && return
        end

        if @order.completed?
          @current_order = nil
          flash.notice = Spree.t(:order_processed_successfully)
          flash['order_completed'] = true
          redirect_to completion_route
        else
          redirect_to checkout_state_path(@order.state)
        end
      else
        render :edit
      end
    end

    private

    def unknown_state?
      (params[:state] && !@order.has_checkout_step?(params[:state])) ||
        (!params[:state] && !@order.has_checkout_step?(@order.state))
    end

    def insufficient_payment?
      params[:state] == "confirm" &&
        @order.payment_required? &&
        @order.payments.valid.sum(:amount) != @order.total
    end

    def correct_state
      if unknown_state?
        @order.checkout_steps.first
      elsif insufficient_payment?
        'payment'
      else
        @order.state
      end
    end

    def ensure_valid_state
      if @order.state != correct_state && !skip_state_validation?
        flash.keep
        @order.update_column(:state, correct_state)
        redirect_to checkout_state_path(@order.state)
      end
    end

    # Should be overriden if you have areas of your checkout that don't match
    # up to a step within checkout_steps, such as a registration step
    def skip_state_validation?
      false
    end

    def load_order_with_lock
      @order = current_order(lock: true)
      redirect_to(spree.cart_path) && return unless @order
    end

    def ensure_valid_state_lock_version
      if params[:order] && params[:order][:state_lock_version]
        @order.with_lock do
          unless @order.state_lock_version == params[:order].delete(:state_lock_version).to_i
            flash[:error] = Spree.t(:order_already_updated)
            redirect_to(checkout_state_path(@order.state)) && return
          end
          @order.increment!(:state_lock_version)
        end
      end
    end

    def set_state_if_present
      if params[:state]
        if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
          redirect_to checkout_state_path(@order.state)
        end
        @order.state = params[:state]
      end
    end

    def ensure_checkout_allowed
      unless @order.checkout_allowed?
        redirect_to spree.cart_path
      end
    end

    def ensure_order_not_completed
      redirect_to spree.cart_path if @order.completed?
    end

    def ensure_sufficient_stock_lines
      if @order.insufficient_stock_lines.present?
        flash[:error] = Spree.t(:inventory_error_flash_for_insufficient_quantity)
        redirect_to spree.cart_path
      end
    end

    # Provides a route to redirect after order completion
    def completion_route(custom_params = nil)
      spree.order_path(@order, custom_params)
    end

    def setup_for_current_state
      method_name = :"before_#{@order.state}"
      send(method_name) if respond_to?(method_name, true)
    end

    def before_address
      # if the user has a default address, a callback takes care of setting
      # that; but if he doesn't, we need to build an empty one here
      @order.bill_address ||= Address.build_default
      @order.ship_address ||= Address.build_default if @order.checkout_steps.include?('delivery')
    end

    def before_delivery
      return if params[:order].present?

      packages = @order.shipments.map(&:to_package)
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
    end

    def before_payment
      if @order.checkout_steps.include? "delivery"
        packages = @order.shipments.map(&:to_package)
        @differentiator = Spree::Stock::Differentiator.new(@order, packages)
        @differentiator.missing.each do |variant, quantity|
          @order.contents.remove(variant, quantity)
        end
      end

      if try_spree_current_user && try_spree_current_user.respond_to?(:payment_sources)
        @payment_sources = try_spree_current_user.payment_sources
      end
    end

    def add_store_credit_payments
      if params.has_key?(:apply_store_credit)
        @order.add_store_credit_payments

        # Remove other payment method parameters.
        params[:order].delete(:payments_attributes)
        params[:order].delete(:existing_card)
        params.delete(:payment_source)

        # Return to the Payments page if additional payment is needed.
        if @order.payments.valid.sum(:amount) < @order.total
          redirect_to checkout_state_path(@order.state) and return
        end
      end
    end

    def rescue_from_spree_gateway_error(exception)
      flash.now[:error] = Spree.t(:spree_gateway_error_flash_for_checkout)
      @order.errors.add(:base, exception.message)
      render :edit
    end

    def check_authorization
      authorize!(:edit, current_order, cookies.signed[:guest_token])
    end
  end
end

app/controllers/spree/checkout_controller_decorator.rb
module Spree
  CheckoutController.class_eval do
    before_filter :coinbase_redirect, :only => [:update]

    private
    def coinbase_redirect
      return unless (params[:state] == "payment") && params[:order][:payments_attributes]

      payment_method = PaymentMethod.find(params[:order][:payments_attributes].first[:payment_method_id])
      if payment_method.kind_of?(Spree::PaymentMethod::Coinbase)
        redirect_to spree_coinbase_redirect_url(:payment_method_id => payment_method.id)
      end
    end
  end
end

app/controllers/spree/my_pays_controller.rb
class Spree::MyPaysController < ApplicationController
  before_action :set_spree_my_pay, only: [:show, :edit, :update, :destroy]

  # GET /spree/my_pays
  # GET /spree/my_pays.json
  def index
    @spree_my_pays = Spree::MyPay.all
  end

  # GET /spree/my_pays/1
  # GET /spree/my_pays/1.json
  def show
  end

  # GET /spree/my_pays/new
  def new
    @spree_my_pay = Spree::MyPay.new
  end

  # GET /spree/my_pays/1/edit
  def edit
  end

  # POST /spree/my_pays
  # POST /spree/my_pays.json
  def create
    @spree_my_pay = Spree::MyPay.new(spree_my_pay_params)

    respond_to do |format|
      if @spree_my_pay.save
        format.html { redirect_to @spree_my_pay, notice: 'My pay was successfully created.' }
        format.json { render :show, status: :created, location: @spree_my_pay }
      else
        format.html { render :new }
        format.json { render json: @spree_my_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spree/my_pays/1
  # PATCH/PUT /spree/my_pays/1.json
  def update
    respond_to do |format|
      if @spree_my_pay.update(spree_my_pay_params)
        format.html { redirect_to @spree_my_pay, notice: 'My pay was successfully updated.' }
        format.json { render :show, status: :ok, location: @spree_my_pay }
      else
        format.html { render :edit }
        format.json { render json: @spree_my_pay.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spree/my_pays/1
  # DELETE /spree/my_pays/1.json
  def destroy
    @spree_my_pay.destroy
    respond_to do |format|
      format.html { redirect_to spree_my_pays_url, notice: 'My pay was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spree_my_pay
      @spree_my_pay = Spree::MyPay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spree_my_pay_params
      params.require(:spree_my_pay).permit(:live, :event_code, :psp_reference, :original_reference, :merchant_reference, :merchant_account_code, :event_date, :success, :payment_method, :operations, :reason, :currency, :value, :processed)
    end
end

app/helpers/spree/my_pays_helper.rb
module Spree::MyPaysHelper
end

app/views/spree/my_pays/_form.html.erb
<%= form_for(spree_my_pay) do |f| %>
  <% if spree_my_pay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spree_my_pay.errors.count, "error") %> prohibited this spree_my_pay from being saved:</h2>

      <ul>
      <% spree_my_pay.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :live %>
    <%= f.check_box :live %>
  </div>

  <div class="field">
    <%= f.label :event_code %>
    <%= f.text_field :event_code %>
  </div>

  <div class="field">
    <%= f.label :psp_reference %>
    <%= f.text_field :psp_reference %>
  </div>

  <div class="field">
    <%= f.label :original_reference %>
    <%= f.text_field :original_reference %>
  </div>

  <div class="field">
    <%= f.label :merchant_reference %>
    <%= f.text_field :merchant_reference %>
  </div>

  <div class="field">
    <%= f.label :merchant_account_code %>
    <%= f.text_field :merchant_account_code %>
  </div>

  <div class="field">
    <%= f.label :event_date %>
    <%= f.datetime_select :event_date %>
  </div>

  <div class="field">
    <%= f.label :success %>
    <%= f.check_box :success %>
  </div>

  <div class="field">
    <%= f.label :payment_method %>
    <%= f.text_field :payment_method %>
  </div>

  <div class="field">
    <%= f.label :operations %>
    <%= f.text_field :operations %>
  </div>

  <div class="field">
    <%= f.label :reason %>
    <%= f.text_area :reason %>
  </div>

  <div class="field">
    <%= f.label :currency %>
    <%= f.text_field :currency %>
  </div>

  <div class="field">
    <%= f.label :value %>
    <%= f.number_field :value %>
  </div>

  <div class="field">
    <%= f.label :processed %>
    <%= f.check_box :processed %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spree/my_pays/edit.html.erb
<h1>Editing Spree My Pay</h1>

<%= render 'form', spree_my_pay: @spree_my_pay %>

<%= link_to 'Show', @spree_my_pay %> |
<%= link_to 'Back', spree_my_pays_path %>

app/views/spree/my_pays/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Spree My Pays</h1>

<table>
  <thead>
    <tr>
      <th>Live</th>
      <th>Event code</th>
      <th>Psp reference</th>
      <th>Original reference</th>
      <th>Merchant reference</th>
      <th>Merchant account code</th>
      <th>Event date</th>
      <th>Success</th>
      <th>Payment method</th>
      <th>Operations</th>
      <th>Reason</th>
      <th>Currency</th>
      <th>Value</th>
      <th>Processed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @spree_my_pays.each do |spree_my_pay| %>
      <tr>
        <td><%= spree_my_pay.live %></td>
        <td><%= spree_my_pay.event_code %></td>
        <td><%= spree_my_pay.psp_reference %></td>
        <td><%= spree_my_pay.original_reference %></td>
        <td><%= spree_my_pay.merchant_reference %></td>
        <td><%= spree_my_pay.merchant_account_code %></td>
        <td><%= spree_my_pay.event_date %></td>
        <td><%= spree_my_pay.success %></td>
        <td><%= spree_my_pay.payment_method %></td>
        <td><%= spree_my_pay.operations %></td>
        <td><%= spree_my_pay.reason %></td>
        <td><%= spree_my_pay.currency %></td>
        <td><%= spree_my_pay.value %></td>
        <td><%= spree_my_pay.processed %></td>
        <td><%= link_to 'Show', spree_my_pay %></td>
        <td><%= link_to 'Edit', edit_spree_my_pay_path(spree_my_pay) %></td>
        <td><%= link_to 'Destroy', spree_my_pay, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Spree My Pay', new_spree_my_pay_path %>

app/views/spree/my_pays/new.html.erb
<h1>New Spree My Pay</h1>

<%= render 'form', spree_my_pay: @spree_my_pay %>

<%= link_to 'Back', spree_my_pays_path %>

app/views/spree/my_pays/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Live:</strong>
  <%= @spree_my_pay.live %>
</p>

<p>
  <strong>Event code:</strong>
  <%= @spree_my_pay.event_code %>
</p>

<p>
  <strong>Psp reference:</strong>
  <%= @spree_my_pay.psp_reference %>
</p>

<p>
  <strong>Original reference:</strong>
  <%= @spree_my_pay.original_reference %>
</p>

<p>
  <strong>Merchant reference:</strong>
  <%= @spree_my_pay.merchant_reference %>
</p>

<p>
  <strong>Merchant account code:</strong>
  <%= @spree_my_pay.merchant_account_code %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @spree_my_pay.event_date %>
</p>

<p>
  <strong>Success:</strong>
  <%= @spree_my_pay.success %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @spree_my_pay.payment_method %>
</p>

<p>
  <strong>Operations:</strong>
  <%= @spree_my_pay.operations %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @spree_my_pay.reason %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @spree_my_pay.currency %>
</p>

<p>
  <strong>Value:</strong>
  <%= @spree_my_pay.value %>
</p>

<p>
  <strong>Processed:</strong>
  <%= @spree_my_pay.processed %>
</p>

<%= link_to 'Edit', edit_spree_my_pay_path(@spree_my_pay) %> |
<%= link_to 'Back', spree_my_pays_path %>